apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazy-caracal
  namespace: app-foo-prd
  labels:
    app: crazy-caracal
    env: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crazy-caracal
      env: prd
  template:
    metadata:
      labels:
        app: crazy-caracal
        env: prd
    spec:
      containers:
      - name: apache1
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
